---
# handlers file for 03-post-setup

- name: Test and restart SSHD
  command: sshd -t
  notify: ["Restart SSHD"]

- name: Restart SSHD
  service:
    name: "ssh"
    state: "restarted"

- name: reload systemctl
  command: systemctl daemon-reload

- name: update grub2
  command: "{{ grub2_update_cmd }} -o {{ grub2_config }}"
  tags: [ "grub", "configuration" ]

- name: update-grub
  command: /usr/sbin/update-grub
- name: Generating Netplan Configuration
  command: netplan generate
  listen: netplan generate config
  notify: netplan apply config
  become: true

- name: Generating Netplan Configuration
  command: netplan generate
  listen: netplan generate config
  notify: netplan apply config
  become: true

- name: Applying Netplan Configuration
  command: netplan apply
  listen: netplan apply config
  become: true
  when: netplan_apply

#- name: restart networkd
#  become: true
#  service:
#    name: systemd-networkd
#    state: restarted

#- name: restart resolved
#  become: true
#  service:
#    name: systemd-resolved
#    state: restarted

#- name: apply network interface
#  become: true
#  shell: netplan apply
