---
# tasks file for ansible-drbd

- import_tasks: install.yml
  tags:
    - drbd
    - drbd_debug
    - drbd-heartbeat
    - drbd-services
    - drbd_install
    - drbd-config
    - drbd-disks

- name: main | updating /etc/hosts (localhost)
  template:
    src: etc/hosts.j2
    dest: /etc/hosts_new
    owner: root
    group: root
    mode: 0644
  become: true
  tags:
    - drbd
    - debian
    - drbd_install
# tasks file for ansible-ntp
- include_tasks: ntp.yml
  when: ansible_os_family == "Debian"
  tags:
    - drbd
    - debian
    - drbd_install
