_users:
  - name: sa
    password: Password
    comment: Test
    uid: 1100
    groups: sudo, users
    createhome: yes # Defaults to yes
    home: /home/sa  # Defaults to /home/<username>
    ssh_key_filename: id_rsa_user
    ssh_passphrase: Password
# ansible web -m ansible.builtin.user -a "name=adambertram uid=1041 group=admin"

_user_volumes:
  - name: "{{ _root_pool }}/home/sa"
    properties:
      mountpoint: /home/sa
  - name: "{{ _root_pool }}/home/user1"
    properties:
      mountpoint: /home/sa

# list of users to add
users: []
# create the users
users_user_create: yes
# default user's dotfiles
users_home_files: []
# users home directory
users_home: /home
# create user's home directory
users_home_create: yes
# default user's primary group for users
users_group:
# default user's secondary groups
users_groups: []
# default user's home directory permissions
users_home_mode: "0755"
# default user login shell
#users_shell:
# default user's ssh key type
users_ssh_key_type: rsa
# default user's ssh key bits
users_ssh_key_generate: yes
users_ssh_key_bits: 2048
# default user's setting for authorized keys exclusive
users_authorized_keys_exclusive: yes
# list of users to be removed
users_remove: []
