_users:
  - name: user1
    password: Password
    comment: AdamListek
    uid: 1077
    group: sudo
    createhome: yes        # Defaults to yes
    home: /home/user1    # Defaults to /home/<username>

# ansible web -m ansible.builtin.user -a "name=adambertram uid=1041 group=admin"
