---

#- name: Distribution
#- debug: msg="1 {{ ansible_distribution }}"
#  tags: zfs_debug
##- name: Distribution version
#- debug: msg="2 {{ ansible_distribution_version}}"
#  tags: zfs_debug
##- name: Distribution major version
#- debug: msg="3 {{ ansible_distribution_major_version }}"
#  tags: zfs_debug
##- name: Print test message
##  debug:
##    msg: " ELSO mount | grep -v zfs | tac | awk '/\/mnt/ {print $3}' | xargs -i{} umount -lf {}"

#- debug: msg="4 {{ release }}"
#  tags: chroot_debug

- name: Verify that the ZFS boot filesystem is recognized
  shell: grub-probe /boot
  register: grub_probe
#  until: grub_probe.stdout.find("ext2") == true
#  retries: 2
#  delay: 1
  tags: chroot_debug

- debug: msg="{{grub_probe.stdout}}"
#- debug: msg="name: rebuild initramfs if neccessary  shell: update-initramfs -c -k all"
  register: grubinstalled
  changed_when: true
  failed_when: false  # dpkg -s returns 1 when packages is not found
  check_mode: yes # this can safely run in check_mode
  when: grub_probe.stdout == "ext2"
  tags: chroot_debug

- debug: msg=" SIKER $$$"
  when: grubinstalled.changed
#  when: grubinstalled.stat.exists
#  when: ansible_facts['os_family'] == "Debian"
  tags: chroot_debug


######################################################################################################

# If you only want to ensure that one user and group exists the following can be used
- debug:  msg="username passwords {{ user_name }} {{ user_password }}"
  tags: chroot_debug

##- name: "elso"
#  command: "zfs create -o mountpoint=/home/{{ user_name }} {{ _root_pool }}/home/{{ user_name }}"
#- debug:  "msg= zfs create -o mountpoint=/home/""{{ user_name }}" "{{ _root_pool }}""/home/""{{ user_name }}"
#  tags: chroot_debug


#- shell: adduser --disabled-password --gecos " " "{{ user_name }}"
#  tags: chroot_debug
#- shell: cp -a /etc/skel/. /home/"{{ user_name }}"
#  tags: chroot_debug
#- shell: chown -R "{{user_name}}:{{user_name}} /home/{{user_name}}"
#  tags: chroot_debug
#- shell: usermod -a -G adm,cdrom,dip,lpadmin,lxd,plugdev,sambashare,sudo "{{user_name}}"
#  tags: chroot_debug
#- shell: echo -e "{{user_name}}:{{_password}}" | chpasswd
#  tags: chroot_debug


- name: create zfs swap
  shell : "zfs create -V 4G -b $(getconf PAGESIZE) -o compression=off -o logbias=throughput -o sync=always -o primarycache=metadata -o secondarycache=none {{ _root_pool }}/swap"
  when:
    - _zfs_swap | default(false) | bool == true
    - _crypt | default(false) | bool == true
    - _raid | default(false) | bool != true
    - _lukscrypt | default(false) | bool  != true
  tags:
    - chroot_debug
    - chroot_configure_swap


#mkswap -f /dev/zvol/$POOL/swap
#echo "/dev/zvol/$POOL/swap none swap defaults 0 0" >> /etc/fstab
#echo RESUME=none > /etc/initramfs-tools/conf.d/resume

#- name: create swap zvol
#  zfs:
#    name: "{{ _root_pool }}/swap "
#    state: present
#    extra_zfs_properties:
#      "{{ zfs_swap_opts }}"
#    when:
#      - _zfs_swap | default(false) | bool == true
#      - _crypt | default(false) | bool == true
#      - _raid | default(false) | bool != true
#      - _lukscrypt | default(false) | bool  != true
#    tags:
#      - chroot_configure_swap

- name: mkswap For an encrypted (native ZFS encryption) single-disk install
  shell: "mkswap -f /dev/zvol/{{_root_pool}}/swap  && echo /dev/zvol/{{_root_pool}}/swap  none swap,defaults 0 0 >> /etc/fstab  && swapon -av"
  when:
    - _crypt | default(false) | bool == true
    - _raid | default(false) | bool != true
    - _zfs_swap | default(false) | bool == true
  tags:
    - chroot_configure_swap
    - chroot_debug

- lineinfile:
    line: "RESUME=none"
    path: /etc/initramfs-tools/conf.d/resume
    create: yes
    state: present
  when:
    - _crypt | default(false) | bool == true
    - _raid | default(false) | bool != true
    - _zfs_swap | default(false) | bool == true
  tags:
    - chroot_configure_swap
    - chroot_debug
