---
- name: Install netplan
  apt:
    name: "{{ netplan_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - netplan_check_install
  tags:
    - chroot_netplan

- name: Capturing Existing Configurations
  find:
    paths: /etc/netplan
    patterns: "*.yml,*.yaml"
  register: _netplan_configs
  tags:
    - chroot_netplan

- debug: var=_netplan_configs
  when: debug is defined and ( debug | bool )
  tags:
    - chroot_netplan

- name: Removing Existing Configurations
  file:
    path: "{{ item['path'] }}"
    state: absent
  become: true
  with_items: "{{ _netplan_configs['files'] }}"
  when:
    - item['path'] != netplan_config_file
    - netplan_configuration != []
    - netplan_remove_existing
  tags:
    - chroot_netplan

- name: Configuring Netplan
  template:
    src: etc/netplan/config.yaml.j2
    dest: "{{ netplan_config_file }}"
    backup: true
  become: true
  when: netplan_configuration != []
  notify: netplan generate config
  tags:
    - chroot_netplan
