---
# Patch a dependency loop:
# For ZFS native encryption or LUKS

- name: Necessary efi
  apt:
    name:
    state: present
  become: true
  with_items:
    - patch

#- name: Patch a dependency loop For ZFS native encryption or LUKS
#  apt: name={{ item }} state=absent
#  with_items:
#   - curl
#   - patch

#- name: Patchadependency
#  shell: >
#    "$(curl https://launchpadlibrarian.net/478315221/2150-fix-systemd-dependency-loops.patch | sed 's|/etc|/lib|;s|\.in$||' | (cd / ; sudo patch -p1))"

######################################################################################################################
# Patch a dependency loop:
# For ZFS native encryption or LUKS

- name: Download file Patchadependency
  get_url:
    url: https://launchpadlibrarian.net/478315221/2150-fix-systemd-dependency-loops.patch
    dest: /2150-fix-systemd-dependency-loops.patch
#    force_basic_auth: yes

#- name: Patching 
#  patch:
#    dest: "/lib/systemd/system-generators/zfs-mount-generator.in"
#    src: zfs-mount-generator.in
#    backup: no

# backup, basedir, binary, dest, ignore_whitespace, remote_src, src, state, strip
- name: set SElinux to enforcing
  become: true
  ansible.posix.patch:
#    state: enforcing
    src: ll
#    src: 2150-fix-systemd-dependency-loops.patch
    basedir: /lib/systemd

#- name: Apply patch to multiple files under basedir0
#  ansible.posix.patch:
#    src: 2150-fix-systemd-dependency-loops.patch
#    basedir: /lib/systemd
#    strip: 1

#- name: Apply patch to multiple files under basedir
#  ansible.posix.patch:
#    src: zfs-mount-generator.in
#    basedir: /lib/systemd/system-generators
#    strip: 1

#- name: Apply patch to multiple files under basedir2
#  ansible.posix.patch:
#    src: zfs-mount.service.in
#    basedir: /lib/systemd/system
#    strip: 1
#- name: Patch CURL
#  shell: patch /lib/systemd/system-generators/zfs-mount-generator.in /opt/zfs-mount-generator.in chdir=/lib/systemd/system-generators

#- name: Patch CURL
#  shell: patch /lib/systemd/system/zfs-mount.service.in /opt/zfs-mount.service.in chdir=/lib/systemd/system
#- name: Patchadependency
#  shell: "curl {{curl_address}} | sed {{curl_sed}} | {{curl_patch}}"
