---
# Setup system groups:
- name: addgroup --system lpadmin
  shell: "addgroup --system lpadmin"
  tags:
    - chroot_users

- name: addgroup --system lxd
  shell: "addgroup --system lxd"
  tags:
    - chroot_users

- name: addgroup --system sambashare
  shell: "addgroup --system sambashare"
  tags:
    - chroot_users

- name: Check if user exists
  command: getent passwd {{ user_name }}
  register: user_on_board
  ignore_errors: yes
  tags:
    - chroot_users

- debug: msg= username passwords {{ user_name }} {{ user_password }}
  tags:
    - chroot_users

- name: Delete user
  user:
    name: "{{ item.name }}"
    state: absent
    remove: true
    force: true
  with_items: "{{ _users }}"
  tags:
    - chroot_users

- name: Adding user
  user:
    name: "{{ item.name }}"
    state: present
    comment: "{{ item.comment }}"
    shell: /bin/bash
    groups: "{{ item.groups }}"
    append: yes
    password: "{{ _root_password_hash }}"
#    password: "{{ userpass | password_hash('sha512') }}"
    update_password: on_create
    create_home: yes
    generate_ssh_key: yes
#    ssh_key_type: rsa
    ssh_key_type: ed25519
    ssh_key_bits: 4096
    ssh_key_file: ".ssh/{{ item.ssh_key_filename }}"
#    ssh_key_passphrase: "{{ssh_passphrase}}"
    force: no
  with_items: "{{ _users }}"
  tags:
    - chroot_users
