---
# defaults file for ansible-etc-hosts
# Defines if all nodes in play should be added to each hosts /etc/hosts
etc_hosts_add_all_hosts: false

# Defines if ipv6 info is included in /etc/hosts
etc_hosts_enable_ipv6: true

# Defines your primary dns suffix
etc_hosts_pri_dns_name: vagrant.local

# Defines if node has static IP.
etc_hosts_static_ip: false

# Defines if ansible_host is used for defining hosts
etc_hosts_use_ansible_ssh_host: true

# Defines if ansible_default_ipv4.address is used for defining hosts
etc_hosts_use_default_ip_address: false


# defaults file for ansible-drbd
drbd_common:
  disk: ''
  net: |
    cram-hmac-alg sha1;
    shared-secret "{{ drbd_network_shared_secret }}";
  handlers: ''
  startup: ''
  options: ''

drbd_disks:
  - device: /dev/drbd0
    disk: /dev/sdc
    filesystem: ext4
    partitions: 1
    mountpoint: /mnt/nfs
    mountopts: defaults
    resource: r0
    state: present
    use_partition: /dev/sdc1

drbd_group: targets

drbd_interface: ens34

drbd_network_shared_secret: wXE8MqVa

drbd_vip: 192.168.100.10

# Debian9/Ubuntu have included drbd support.
drbd_deb_packages: ['drbd8-utils']
# Additional yum repo required. See ELREPO for prebuilt RHEL RPMS, or your local site administrator.
drbd_rpm_packages: ['drbd84-utils', 'kmod-drbd84']

# Toggle
drbd_use_heartbeat: true
drbd_use_parted: true
drbd_unicast_mode: false
drbd_unicast_port: 694

# defaults file for ansible-ntp
# Defines if host is ntp_master

# Defines whether a fallback server should be configured or not
ntp_enable_fallback_server: false

# Defines an ntp fallback to server use when ntp_enable_fallback_server is true
ntp_fallback_server: ntp.ubuntu.com

# set ntp_master to true on specific group_vars/group
ntp_master: false

# Define your ntp_master_servers
ntp_master_servers:
  - 0.ubuntu.pool.ntp.org
  - 1.ubuntu.pool.ntp.org
  - 2.ubuntu.pool.ntp.org
  - 3.ubuntu.pool.ntp.org

# Defines your primary domain name (FQDN)
ntp_pri_domain_name: example.org

# Defines internal ntp servers for clients to poll
ntp_servers:
  []
  # - "ntp1.{{ ntp_pri_domain_name }}"
  # - "ntp2.{{ ntp_pri_domain_name }}"
