---
- name: restart docker
  service: "name=docker state={{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: reload systemd docker
  # systemd module not available before ansible version 2.2
  #systemd: daemon_reload=yes name=docker
  # work around - use command
  command: systemctl daemon-reload
  notify: restart docker
